#!/usr/bin/env bash
if [ "$EUID" -eq 0 ]
then
  logd=/var/log/servinit
  systemctl stop servinit
  cp -r ./bash /usr/local/servinit
  cp -r ./messages /usr/local/servinit
  cp ./servinit.service /etc/systemd/system
  chmod +x /usr/local/servinit/bash/*
  echo "Updated necessary files. Starting service."
  systemctl daemon-reload 2>>$logd\/errors.log >> $logd\/standard.log
  systemctl start servinit 2>>$logd\/errors.log >> $logd\/standard.log
  if [ $? -eq 0 ]
  then
    echo "The service has been restarted. Check the /var/log/servinit directory for logs."
  elif [ $? -eq 1 ]
  then
    echo "Servinit service not properly restarted. Please run 'systemctl status servinit' to investigate."
  fi
else
  echo "Not running as 'root' user! Please run as 'root' to properly start and install this service."
fi
