#SingleInstance, Force
SendMode Input
SetWorkingDir, %A_ScriptDir%

; This script is designed to initialize a Debian based server for use with bash scripts
; It will ask the user if the openssh-server is installed on the server
; It will then ask the user for the IP address of the server, the username, and the password
; It will next ask if the user has an SSH key, if not it will ask if the user wants to create one
; If the user does not want to create an SSH key, the script will ask for the user's password
; If the user does have an SSH key, the script will then ask for the user's password
; The script will then ask for the port number of the server, if the user has not changed the port number it should be 22
; The script will then connect to the server and initialize it for use with future bash scripts, for example, it will create the necessary directories and set the necessary permissions and then run the init script which will make sure that the 'jq' package and the 'Docker Compose' pakage are installed on the server
; The script will then exit
; The init script provided is set up for my use case, you will need to modify it to fit your use case.
; I thought it would be useful to have a Microsoft Windows capable script to initialize a server for use with bash scripts.
; This script is designed to be used with the Windows PowerShell 7.0.3, it may work with other versions of PowerShell, but I have not tested it with other versions.
; This script is also designed to be used with the OpenSSH-Client service on Microsoft Windows, though it may work with other SSH clients, but I have not tested it with other SSH clients.
; This script is also designed to be used with the 'openssh-server' service on an Ubuntu Server, it should work fine for any Debian based Linux installations.
; This script also assumes that the user has the necessary permissions to perform the tasks required to initialize the server.
; As always, please use scripts cautiously and responsibly.
; This script does not store your passwords or any other sensitive information, it is designed to be used in a secure environment.
; The SSH Key generated by this script will be stored in the path you provide, it will never be sent to or stored at any other location by the script nor any child scripts it may run.
; Please omit/'do no use' any file extensions (ie: *.exe, *.pub, *.txt) in the next window. It is already accounted for in the script.
; Depending on your environment your passwords could potentially be visible to bad actors due to the way the script stores variables in RAM which could then be accessed by a rogue 'program/virus', though rare for non-targets and hardened against with the right settings in Windows 11, please use this script in a secure environment.

Command1 := "scp -rP %Port% %SSHKeyPath%.pub %UserName%@%Host%:~/.ssh/authorized_keys"
Command2 := "scp -rP %Port% %InitScriptPath% %UserName%@%Host%:~/scripts/init/"
Command3 := "ssh %UserName%@%Host% -p %Port%"
Command4 := "ssh-keygen -b 4096 -t rsa -f %SSHKeyPath%"
terminal := "C:\Program Files\PowerShell\7\pwsh.exe"
rCommand1 := "mkdir ~/.ssh"
rCommand2 := "chmod 700 ~/.ssh"
rCommand3 := "mkdir -p ~/scripts/init"
rCommand4 := "chmod 700 ~/scripts/init"
rCommand5 := "chmod +x ~/scripts/init/init.sh"
rCommand6 := "~/scripts/init/init.sh"
Logout := "logout"

MsgBox, 4, 4096, 32, 'Initialize Server', 'Is openssh-server installed on the target server? (yes/no)'
    IfMsgBox = yes ; to get to here, the users was asked if the openssh server is installed on the server, and they answered yes
        InputBox, Host, 'Initialize Server', 'Please enter the 'Host' information of the server: ', nope, 400, 200, 0, 0, Locale, IP Address/Hostname/Domain-Name
        Sleep, 500
        MsgBox, 4, 4096, 32, 'Initialize Server', 'Do you have an SSH key? (yes/no)'
            IfMsgBox = yes ; to get to here, the user was asked if they have an SSH key, and they answered yes
                MsgBox, 4096, 64, 1, 256, 'Initialize Server', 'Please omit/'do no use' any file extensions (ie: *.exe, *.pub, *.txt) in the next window. It is already accounted for in the script.'
                    IfMsgBox Ok ; to get to here, the user was asked to omit/'do no use' any file extensions in the next window, and they clicked Ok
                        InputBox, SSHKeyPath, 'Initialize Server', 'Enter the full path for the sshkey storage: ', nope, 400, 200, 0, 0, Locale
                        Sleep, 500
                        InputBox, Passwd, 'Initialize Server: What is the user's password?', 'Enter the user's password of the server: ', HIDE 400, 200, 0, 0, Locale, Password
                        Sleep, 500
                        InputBox, UserName, 'Initialize Server', 'Enter the user's username on the server: ', nope, 400, 200, 0, 0, Locale, Username
                        Sleep, 500
                        MsgBox, 4, 4096, 32, 'Did you change the ssh port number used by the server? (yes/no)'
                            IfMsgBox = yes ; to get to here, the user was asked if they changed the ssh port number used by the server, and they answered yes
                                InputBox, Port, 'Initialize Server', 'Enter the SSH port number of the server, if you haven't changed it you should be able to just click Ok: ', nope, 400, 200, 0, 0, Locale, Port
                                InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the init script: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                                Sleep, 500
                                Run, %terminal%
                                Sleep, 500
                                Send, %Command3%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %rCommand1%{Enter}
                                Sleep, 10000
                                Send, %rCommand2%{Enter}
                                Sleep, 10000
                                Send, %rCommand3%{Enter}
                                Sleep, 10000
                                Send, %rCommand4%{Enter}
                                Sleep, 10000
                                Send, %Logout%{Enter}
                                Sleep, 10000
                                Send, %Command4%{Enter}
                                Sleep, 10000
                                Send, {Enter}
                                Sleep, 10000
                                Send, {Enter}
                                Sleep, 10000
                                Send, %Command1%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %Command2%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %Command3%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %rCommand5%{Enter}
                                Sleep, 10000
                                Send, %rCommand6%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 1800000
                                Send, %Logout%{Enter}
                                Sleep, 10000
                                Send, Exit{Enter}
                                Sleep, 1000
                                MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                                    IfMsgBox = Ok ; to get to here, the user was informed that the server has been initialized, and they clicked Ok
                                        ExitApp
                            IfMsgBox = no ; to get to here, the user was asked if they changed the ssh port number used by the server, and they answered no
                                Port := 22
                                InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the init script: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                                Sleep, 500
                                Run, %terminal%
                                Sleep, 500
                                Send, %Command3%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %rCommand1%{Enter}
                                Sleep, 10000
                                Send, %rCommand2%{Enter}
                                Sleep, 10000
                                Send, %rCommand3%{Enter}
                                Sleep, 10000
                                Send, %rCommand4%{Enter}
                                Sleep, 10000
                                Send, %Logout%{Enter}
                                Sleep, 10000
                                Send, %Command4%{Enter}
                                Sleep, 10000
                                Send, {Enter}
                                Sleep, 10000
                                Send, {Enter}
                                Sleep, 10000
                                Send, %Command1%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %Command2%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %Command3%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 10000
                                Send, %rCommand5%{Enter}
                                Sleep, 10000
                                Send, %rCommand6%{Enter}
                                Sleep, 10000
                                Send, %Passwd%{Enter}
                                Sleep, 1800000
                                Send, %Logout%{Enter}
                                Sleep, 10000
                                Send, Exit{Enter}
                                Sleep, 1000
                                MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                                    IfMsgBox = Ok ; to get to here, the user was informed that the server has been initialized, and they clicked Ok
                                        ExitApp
                    IfMsgBox = Cancel ; to get to here, the user was asked to omit/'do no use' any file extensions in the next window, and they clicked Cancel
                        ExitApp
                MsgBox, 4, 4096, 32, 'Initialize Server', 'Do you want an SSH Key to connect to your server with? (yes/no)'
                    IfMsgBox = yes ; to get to here, the user was asked if they want an SSH Key to connect to their server with, and they answered yes
                        MsgBox, 4096, 64, 1, 256, 'Initialize Server', 'Please omit/'do no use' any file extensions (ie: *.exe, *.pub, *.txt) in the next window.'
                            IfMsgBox Ok ; to get to here, the user was asked to omit/'do no use' any file extensions in the next window, and they clicked Ok
                                InputBox, SSHKeyPath, 'Initialize Server', 'Enter the full path for the sshkey storage: ', nope, 400, 200, 0, 0, Locale
                                Sleep, 500
                                InputBox, Passwd, 'Initialize Server: What is the target user's password?', 'Enter the user's password of the server: ', HIDE 400, 200, 0, 0, Locale, Password
                                Sleep, 500
                                InputBox, UserName, 'Initialize Server', 'Enter the target user's username on the server: ', nope, 400, 200, 0, 0, Locale, Username
                                Sleep, 500
                                MsgBox, 4, 'Did you change the ssh target port? (yes/no)'
                                    IfMsgBox Yes ; to get to here, the user was asked if they changed the ssh target port, and they answered yes
                                        InputBox, Port, 'Initialize Server', 'Enter the SSH target port of the server: ', nope, 400, 200, 0, 0, Locale, Port
                                        Sleep, 500
                                        InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the source init script folder: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                                        Sleep, 500
                                        Run, %terminal%
                                        Sleep, 500
                                        Send, %Command3%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand1%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand2%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand3%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand4%{Enter}
                                        Sleep, 10000
                                        Send, %Logout%{Enter}
                                        Sleep, 10000
                                        Send, %Command1%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %Command2%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %Command3%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand5%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand6%{Enter}
                                        Sleep, 1800000
                                        MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                                            IfMsgBox = Ok ; to get to here, the user was informed that the server has been initialized, and they clicked Ok
                                                ExitApp
                                    IfMsgBox = no ; to get to here, the user was asked if they changed the ssh target port, and they answered no
                                        Port := 22
                                        InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the init script: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                                        Sleep, 500
                                        Run, %terminal%
                                        Sleep, 500
                                        Send, %Command3%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand1%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand2%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand3%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand4%{Enter}
                                        Sleep, 10000
                                        Send, %Logout%{Enter}
                                        Sleep, 10000
                                        Send, %Command1%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %Command2%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %Command3%{Enter}
                                        Sleep, 10000
                                        Send, %Passwd%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand5%{Enter}
                                        Sleep, 10000
                                        Send, %rCommand6%{Enter}
                                        Sleep, 1800000
                                        MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                                            IfMsgBox = Ok ; to get to here, the user was informed that the server has been initialized, and they clicked Ok
                                                ExitApp
                            IfMsgBox = Cancel ; to get to here, the user was asked to omit/'do no use' any file extensions in the next window, and they clicked Cancel
                                ExitApp
            IfMsgBox = no ; to get to here, the user was asked if they have an SSH key, and they answered no
                InputBox, Passwd, 'Initialize Server: What is the user's password?', HIDE 400, 200, 0, 0, Locale, Password
                Sleep, 500
                InputBox, UserName, 'Initialize Server', 'Enter the user's username on the server: ', nope, 400, 200, 0, 0, Locale, Username
                Sleep, 500
                MsgBox, 4, 4096, 32, 'Did you change the ssh port number used by the server? (yes/no)'
                    IfMsgBox = yes ; to get to here, the user was asked if they changed the ssh port number used by the server, and they answered yes
                        InputBox, Port, 'Initialize Server', 'Enter the SSH port number of the server, if you haven't changed it you should be able to just click Ok: ', nope, 400, 200, 0, 0, Locale, Port
                        InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the init script: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                        Sleep, 500
                        Run, %terminal%
                        Sleep, 500
                        Send, %Command3%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %rCommand3%{Enter}
                        Sleep, 10000
                        Send, %rCommand4%{Enter}
                        Sleep, 10000
                        Send, %Logout%{Enter}
                        Sleep, 10000
                        Send, %Command2%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %Command3%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %rCommand5%{Enter}
                        Sleep, 10000
                        Send, %rCommand6%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 1800000
                        MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                            IfMsgBox = Ok ; to get to here, the user was informed that the server has been initialized, and they clicked Ok
                                ExitApp
                    IfMsgBox = no ; to get to here, the user was asked if they changed the ssh port number used by the server, and they answered no
                        Port := 22
                        InputBox, InitScriptPath, 'Initialize Server', 'Please enter the full path for the init script: ', nope, 400, 200, 0, 0, Locale, Path-to-Init-Script-Folder
                        Sleep, 500
                        Run, %terminal%
                        Sleep, 500
                        Send, %Command3%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %rCommand1%{Enter}
                        Sleep, 10000
                        Send, %rCommand2%{Enter}
                        Sleep, 10000
                        Send, %rCommand3%{Enter}
                        Sleep, 10000
                        Send, %rCommand4%{Enter}
                        Sleep, 10000
                        Send, %Logout%{Enter}
                        Sleep, 10000
                        Send, %Command1%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %Command2%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %Command3%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 10000
                        Send, %rCommand5%{Enter}
                        Sleep, 10000
                        Send, %rCommand6%{Enter}
                        Sleep, 10000
                        Send, %Passwd%{Enter}
                        Sleep, 1800000
                        Send, %Logout%{Enter}
                        Sleep, 10000
                        Send, Exit{Enter}
                        Sleep, 1000
                        MsgBox, 0, 4096, 64, 'Server has been initialized, you may now use the server with bash scripts.'
                            IfMsgBox = Ok ; 
                                ExitApp
    IfMsgBox = no ; to get to here, the user was asked if the openssh server is installed on the server, and they answered no
        MsgBox, 0, 4096, 'Initialize Server', 'Please run "apt install openssh-server" if you are logged in as root, otherwise use "sudo apt install openssh-server", on the target system and try again.'
            IfMsgBox = Ok ; to get to here, the user was informed that the openssh server is not installed on the server, and they clicked Ok
                ExitApp