#!/usr/bin/env bash
if [ ! -d /var/log/servinit ]
  then mkdir -p /var/log/servinit
fi
logd=/var/log/servinit
for package in bsdutils bsdmainutils bsdextrautils containerd.io dnsutils docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin jq nano dc bc;
do
  if dpkg-query -W -f='${Status}' $package 2>>$logd\/errors.log | grep -q "install ok installed"; then
        if [ "$EUID" -eq 0 ]
          then 
            apt update && apt upgrade -y $package 2>>$logd\/errors.log >> $logd\/standard.log
        else
            echo "Not running as root user! Exiting!" >> $logd\/errors.log
        fi
    else
        echo "$package not in list! Skipping" >> $logd\/errors.log
    fi
done
