#!/usr/bin/env bash
if [ ! -d /var/log/servinit ]
then 
  mkdir -p /var/log/servinit
fi
if [ ! -d /tmp/servinit ]
then
  mkdir -p /tmp/servinit
fi
logd=/var/log/servinit
bash /usr/local/servinit/bash/alias-checker
sleep 900
while true
do
  pgrep -f server-control >> $logd\/standard.log
  if [ $? -eq 1 ]
  then
    bash /usr/local/servinit/bash/server-control
    if [ $? -eq 1 ]
    then
      echo "An error has occured!" >> $logd\/errors.log
    fi
  fi
  sleep 300
done
