#!/usr/bin/env bash

if [ $HOSTNAME == 'docker-server-1' ]
then
    echo 'Success!'
elif [ $HOSTNAME == 'docker-server-2' ]
then
    echo 'Success!'
elif [ $HOSTNAME == 'docker-server-3' ]
then
    echo 'Success!'
elif [ $HOSTNAME == 'prox1' ]
then
    echo 'Success!'
elif [ $HOSTNAME == 'CamsGamingPC' ]
then
    echo 'Success!'
    bash ~/scripts/bash/copy
else
    clear
    echo $(base64 --decode ~/scripts/messages/failure-to-launch.txt)
    exit
fi
