#!/usr/bin/env bash
if [ $HOSTNAME == 'docker-server-1' ]
then
    bash /usr/local/servinit/bash/dep-installer
    while true
    do
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep 86400
    done
elif [ $HOSTNAME == 'docker-server-2' ]
then
    bash /usr/local/servinit/bash/dep-installer
    while true
    do
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep 86400
    done
elif [ $HOSTNAME == 'docker-server-3' ]
then
    bash /usr/local/servinit/bash/dep-installer
    while true
    do
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep 86400
    done
elif [ $HOSTNAME == 'prox1' ]
then
    bash /usr/local/servinit/bash/dep-installer
    while true
    do
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/host-backup
      sleep 86400
    done
else
    clear
    echo $(base64 --decode /usr/local/servinit/messages/failure-to-launch.txt)
    exit 1
fi
