#!/usr/bin/env bash
stime=86400
if [ "$HOSTNAME" == "docker-server-1" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep $stime
    done
elif [ "$HOSTNAME" == "docker-server-2" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep $stime
    done
elif [ "$HOSTNAME" == "docker-server-3" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep $stime
    done
elif [ "$HOSTNAME" == "prox1" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/host-backup
      sleep $stime
    done
elif [ "$HOSTNAME" == "testing-22.04" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep $stime
    done
elif [ "$HOSTNAME" == "OptMicBackupPC" ]
then
    while true
    do
      bash /usr/local/servinit/bash/lpas
      bash /usr/local/servinit/bash/dep-updater
      bash /usr/local/servinit/bash/backup
      sleep $stime
    done
else
    clear
    echo "$(base64 --decode /usr/local/servinit/messages/failure-to-launch.txt)"
    exit 1
fi
