#!/usr/bin/env bash
logd=/var/log/servinit
pgrep -f initialize > /dev/null
if [ $? -eq 0 ]
then
  kill $(pgrep -f initialize) 2>>$logd\/errors.log >> $logd\/standard.log
  echo "Initialize script has been stopped" 2>>$logd\/errors.log >> $logd\/standard.log
else
  echo "Initialize script not running" 2>>$logd\/errors.log >> $logd\/standard.log
fi
pgrep -f server-control > /dev/null
if [ $? -eq 0 ]
then
  kill $(pgrep -f server-control) 2>>$logd\/errors.log >> $logd\/standard.log
  echo "Server control script has been stopped" 2>>$logd\/errors.log >> $logd\/standard.log
else
  echo "Server control script not running" 2>>$logd\/errors.log >> $logd\/standard.log
fi
